In [34]:
import pandas as pd 
import numpy as np
import os
from sklearn.tree import DecisionTreeClassifier 
import matplotlib.pyplot as plt 
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix 

In [53]:
# ------------ QUESTION 1 --------------
# ------- model creation -------- 
from MakeDataset import X_train,y_train, X_test
from sklearn.preprocessing import MinMaxScaler

X_train_total_acc = np.sum(X_train**2, axis=2)
X_test_total_acc = np.sum(X_test**2, axis=2)

model = DecisionTreeClassifier()
model.fit(X_train_total_acc, y_train)

scaler = MinMaxScaler()
x_train_scaled = scaler.fit_transform(X_train_total_acc)
model_with_normalized_feature = DecisionTreeClassifier()
model_with_normalized_feature.fit(x_train_scaled, y_train)


DecisionTreeClassifier()

In [54]:
import pandas as pd
import os

ACTIVITIES = {
    1: 'WALKING',
    2: 'WALKING_UPSTAIRS',
    3: 'WALKING_DOWNSTAIRS',
    4: 'SITTING',
    5: 'STANDING',
    6: 'LAYING',
}

x_test_personal = []
y_test_personal = []

# Path to the main directory containing activity subfolders


for label, activity in ACTIVITIES.items():
    activity_folder = os.path.join('personal_data', activity)
    
    if os.path.exists(activity_folder):
        for filename in os.listdir(activity_folder):
            if filename.endswith('.csv'):
                file_path = os.path.join(activity_folder, filename)
                
                # Read 500 values from the 'aT' column, starting from offset 250
                data = pd.read_csv(file_path, skiprows=range(1, 250), nrows=500)
                data = data.iloc[:, -1:]
                data = data.T
                x_test_personal.append(data)
                y_test_personal.append(label)

# Concatenate all dataframes in x_test
x_test_personal = pd.concat(x_test_personal, ignore_index=True)

# Convert y_test to a pandas Series
y_test_personal = pd.Series(y_test_personal)

# Display the first few rows of x_test and y_test
print(x_test_personal.shape)
print(y_test_personal.shape)

(36, 500)
(36,)


In [55]:
y_pred_personal = model.predict(x_test_personal)

# Calculate Accuracy
accuracy = accuracy_score(y_test_personal, y_pred_personal)
print(f"Accuracy: {accuracy:.2f}")

# Calculate Precision 
precision = precision_score(y_test_personal, y_pred_personal, average='weighted')
print(f"Precision : {precision:.2f}")

# Calculate Recall
recall = recall_score(y_test_personal, y_pred_personal, average='weighted')
print(f"Recall : {recall:.2f}")

# Confusion Matrix 
cm = confusion_matrix(y_test_personal, y_pred_personal)

print("Confusion Matrix")
print(cm)



Accuracy: 0.11
Precision : 0.04
Recall : 0.11
Confusion Matrix
[[4 1 0 0 0 1]
 [6 0 0 0 0 0]
 [5 1 0 0 0 0]
 [0 0 6 0 0 0]
 [0 0 6 0 0 0]
 [0 0 6 0 0 0]]


d:\iitgn_study\ml_assignments\es335-24-fall-assignment-1\.venv\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [56]:
#  ---------- QUESTION 2 ----------

x_test_personal_scaled = scaler.transform(x_test_personal)
y_pred_personal = model_with_normalized_feature.predict(x_test_personal_scaled)


# Calculate Accuracy
accuracy = accuracy_score(y_test_personal, y_pred_personal)
print(f"Accuracy: {accuracy:.2f}")

# Calculate Precision 
precision = precision_score(y_test_personal, y_pred_personal, average='weighted')
print(f"Precision : {precision:.2f}")

# Calculate Recall
recall = recall_score(y_test_personal, y_pred_personal, average='weighted')
print(f"Recall : {recall:.2f}")

# Confusion Matrix 
cm = confusion_matrix(y_test_personal, y_pred_personal)

print("Confusion Matrix")
print(cm)


Accuracy: 0.14
Precision : 0.10
Recall : 0.14
Confusion Matrix
[[4 1 0 0 0 1]
 [5 1 0 0 0 0]
 [5 1 0 0 0 0]
 [0 0 6 0 0 0]
 [0 0 6 0 0 0]
 [0 0 6 0 0 0]]


d:\iitgn_study\ml_assignments\es335-24-fall-assignment-1\.venv\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


#### Question (iii)

In [57]:
import pandas as pd 
from langchain_groq.chat_models import ChatGroq

In [58]:
from config import API
# Groq API and Models 
Groq_Token = API  # Do not share this key with anyone

groq_models = {"llama3-70b": "llama3-70b-8192", "mixtral": "mixtral-8x7b-32768", "gemma-7b": "gemma-7b-it","llama3.1-70b":"llama-3.1-70b-versatile","llama3-8b":"llama3-8b-8192","llama3.1-8b":"llama-3.1-8b-instant","gemma-9b":"gemma2-9b-it"}

In [59]:
# using raw accelerometer data
from MakeDataset import X_train,X_test,y_train,y_test

X_train_total_acc = np.sum(X_train**2, axis=2)



In [60]:
Accelerometer_X_train = X_train_total_acc
Accelerometer_Y_train = y_train
Accelerometer_X_test = x_test_personal
Accelerometer_Y_test = y_test_personal

In [61]:
dictionary = {
    1 : "Walking",
    2 : "Walking upstairs",
    3 : "Walkimg downstairs",
    4 : "Sitting",
    5 : "Standing",
    6 : "Laying"
}

In [62]:
Acclerometer_examples = {
    "Laying" : [0.991],
    "Sitting" : [1.019],
    "Standing" : [1.063],
    "Walking" : [2.243],
    "Walking Downstairs" : [0.722],
    "Walking Upstairs" : [0.984] 
}

In [45]:
def few_shot(X,examples):
    df = pd.DataFrame(X)
    fewshot = []
    for index, row in df.head(500).iterrows():
        query = f"""

        I am providing you the accelerometer data as:

        {row}

        Here the activities can be as given in the dictionary:

        {dictionary}

        In the dictionary, an integer corresponding to the activities is provided. Use those integers to denote your response.

        Now, based on this accelerometer data and using the dictionary, tell me the type of activity that is performed.

        Here are few examples for you

        {examples}

        Use these examples and the values provided to find your prediction of the activity

        Don't give any explaination just print the answer, as integer
        """

        model_name = "gemma-7b"  # Choose the model
        llm = ChatGroq(model=groq_models[model_name], api_key=Groq_Token, temperature=0)
        answer = llm.invoke(query)

        fewshot.append(answer.content)
    
    print(fewshot)
    return fewshot

In [46]:
fewshot_response = few_shot(Accelerometer_X_test,Acclerometer_examples)

BadRequestError: Error code: 400 - {'error': {'message': 'Organization has been restricted. Please reach out to support if you believe this was in error.', 'type': 'invalid_request_error', 'code': 'organization_restricted'}}